InventoryManagerApp.Web/Areas/Admin/Controllers/ClothesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using InventoryManagerApp.Services.Admin.Models;
using InventoryManagerApp.Services.Admin;
using InventoryManagerApp.Web.Controllers;

namespace InventoryManagerApp.Web.Areas.Admin.Controllers
{
    public class ClothesController : BaseAdminController
    {
        private readonly IAdminClotheService clothes;

        public ClothesController(IAdminClotheService clothes)
        {
            this.clothes = clothes;
        }


        public IActionResult Create()
            => View();

        [HttpPost]
        public async Task<IActionResult> Create(AdminClotheModel model)
        {
            await this.clothes.CreateAsync(model.Name, model.Type, model.Quantity, model.Size, model.SinglePrice, model.PictureUrl, model.Description);

            return RedirectToAction(nameof(HomeController.Index),"Home",new { area=string.Empty });
        }

        public IActionResult Edit(int id)
        {
            if (!this.clothes.IsExists(id))
            {
                return NotFound(); 
            }

            var clothe = this.clothes.ById(id);

            return View(new AdminClotheModel
            {
                Id = id,
                Name=clothe.Name,
                Type=clothe.Type,
                Quantity=clothe.Quantity,
                Size=clothe.Size,
                SinglePrice=clothe.SinglePrice,
                PictureUrl=clothe.PictureUrl,
                Description=clothe.Description
            });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AdminClotheModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await this.clothes.EditAsync(id, model.Name, model.Type, model.Quantity, model.Size, model.SinglePrice, model.PictureUrl, model.Description);

            return RedirectToAction(nameof(HomeController.Details), "Home", new { area = string.Empty, id = id.ToString() });
        }

        public IActionResult Delete(int id) => View(id);

        public async Task<IActionResult> Remove(int id)
        {
            var clothe = this.clothes.ById(id);

            if (clothe==null)
            {
                return NotFound();
            }

            await this.clothes.Delete(id);

            return RedirectToAction(nameof(HomeController.Index),"Home",new { area = string.Empty });
        }
    }
}

InventoryManagerApp.Web/Areas/Admin/Views/Clothes/Create.cshtml
@model AdminClotheModel

@{
    ViewData["Title"] = "Create Clothe";
}

<h2>@ViewData["Title"]</h2>

@{ 
    Html.RenderPartial("_ClothePartial");
}

InventoryManagerApp.Web/Areas/Admin/Views/Clothes/Delete.cshtml
@model int

@{
    ViewData["Title"] = "Delete Clothe";
}

<h2>@ViewData["Title"]</h2>

<h3>Are you sure you want to delete this clothe?</h3>
<a asp-controller="Home" asp-action="index" class="btn btn-default">Back</a>
<a asp-area="Admin" asp-controller="Clothes" asp-action="Remove" asp-route-id="@Model" class="btn btn-danger">Confirm Delete</a>

InventoryManagerApp.Web/Areas/Admin/Views/Clothes/Edit.cshtml
@model AdminClotheModel

@{
    ViewData["Title"] = $"Edit Clothe: {Model.Name}";
}

<h2>@ViewData["Title"]</h2>

@{ 
    Html.RenderPartial("_ClothePartial");
}

InventoryManagerApp.Web/Areas/Admin/Views/Clothes/_ClothePartial.cshtml
@model AdminClotheModel

<head>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
    <script>tinymce.init({ selector: '#Content' });</script>
</head>

<div class="row">
    <div class="col-md-8">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Size"></label>
                <input asp-for="Size" class="form-control" />
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SinglePrice"></label>
                <input asp-for="SinglePrice" class="form-control" />
                <span asp-validation-for="SinglePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PictureUrl"></label>
                <input asp-for="PictureUrl" rows="30" class="form-control" />
                <span asp-validation-for="PictureUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-group">Save Clothe</button>
        </form>
    </div>
</div>

@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
}